Allow failure of tests with dev branches

diff --git a/.github/workflows/activerecord_head.yml b/.github/workflows/activerecord_head.yml
--- a/.github/workflows/activerecord_head.yml
+++ b/.github/workflows/activerecord_head.yml
@@ -8,7 +8,6 @@ on:
 
 jobs:
   test:
-
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -23,8 +22,5 @@ jobs:
         ruby-version: ${{ matrix.ruby_version }}
         bundler-cache: true
     - name: Run tests
-      run: bundle exec rspec
-    - name: Coveralls
-      uses: coverallsapp/github-action@master
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
+      # Allow tests to run on Active Record head without failing the pipeline
+      run: bundle exec rspec || true
diff --git a/.github/workflows/ruby_head.yml b/.github/workflows/ruby_head.yml
--- a/.github/workflows/ruby_head.yml
+++ b/.github/workflows/ruby_head.yml
@@ -8,8 +8,8 @@ on:
 
 jobs:
   test:
-
     runs-on: ubuntu-latest
+    continue-on-error: true
     strategy:
       matrix:
         gemfile: [ activerecord_6.1, activerecord_7.0, activerecord_7.1 ]
@@ -23,8 +23,5 @@ jobs:
         ruby-version: head
         bundler-cache: true
     - name: Run tests
-      run: bundle exec rspec
-    - name: Coveralls
-      uses: coverallsapp/github-action@master
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
+      # Allow tests to run on Ruby head without failing the pipeline
+      run: bundle exec rspec || true
